"""Offline corpus/evidence regressions using invented fixtures only."""
import copy
from contextlib import redirect_stdout
import io
import json
from pathlib import Path
from tempfile import TemporaryDirectory
import unittest
from unittest.mock import patch
import numpy as np
from ml.data_pipeline import ROOT, digest, write_json
from ml.experiment import CANDIDATES
from ml.generalization.evaluate import POLICY as V2_POLICY, evaluate_records
from ml.validation_corpus import data, evaluate, fetch
from ml.validation_corpus.text import feature_text

def row(i=0, label=0, source="a", role="train", reality="REAL", **kwargs):
    word = "item" + chr(97 + i // 26 % 26) + chr(97 + i % 26)
    body = ("meeting agenda colleague report team" if label == 0 else "urgent account password verify suspended") + " " + word
    defaults = dict(source=source, source_id=str(i), label=label, body=body,
                    role=role, reality=reality, date_start="2020-01-01", date_end="2020-01-01",
                    date_quality="DOCUMENTED_MESSAGE_DATE")
    defaults.update(kwargs)
    return data.normalize_example(defaults)

def batch(count=80, offset=0, **kwargs):
    return [row(i+offset, i % 2, **kwargs) for i in range(count)]

def perfect_evaluation():
    rows = batch(200, role="test")
    return evaluate_records(rows, [r["label"] * .98 + .01 for r in rows], .5)

def perfect_evidence():
    return {"modern_real_email_phishing":100, "synthetic_malicious_fraction":0.,
            "unknown_malicious_fraction":0., "external_real_email_counts":{"0":100,"1":100}}

class TaggingTests(unittest.TestCase):
    def test_valid_tags(self):
        for tag in data.TAGS:
            with self.subTest(tag=tag):
                r = row(reality=tag)
                self.assertEqual(r["reality"],tag)
                self.assertEqual(r["synthetic"],tag=="SYNTHETIC")

    def test_unspecified_tag_is_unknown(self):
        r = data.normalize_example({"source":"a","source_id":"u","label":0,"body":"hello team","role":"train"})
        self.assertEqual(r["reality"],"UNKNOWN")

    def test_invalid_tag_rejected(self):
        for tag in ("real","SIMULATED","",None):
            with self.subTest(tag=tag), self.assertRaises(ValueError):
                row(reality=tag)

    def test_bool_label_rejected(self):
        with self.assertRaises(ValueError): row(label=True)

    def test_missing_source_rejected(self):
        with self.assertRaises(ValueError): row(source="")

    def test_overlap_single_class(self):
        self.assertEqual(data.overlap_quality([row()]),"SINGLE_CLASS")

    def test_overlap_both_real(self):
        self.assertEqual(data.overlap_quality(batch(10)),"BOTH_CLASSES_REAL")

    def test_overlap_synthetic(self):
        self.assertEqual(data.overlap_quality(batch(10,reality="SYNTHETIC")),"BOTH_CLASSES_SYNTHETIC")

    def test_overlap_mixed(self):
        self.assertEqual(data.overlap_quality([row(),row(1,1,reality="UNKNOWN")]),"BOTH_CLASSES_MIXED_OR_UNKNOWN")

    def test_summary_keeps_reality_and_class_separate(self):
        s=data.summary([row(),row(1,1,reality="SYNTHETIC"),row(2,1,reality="UNKNOWN")])
        self.assertEqual(s["reality_class_counts"]["REAL"],{"0":1,"1":0})
        self.assertEqual(s["reality_class_counts"]["SYNTHETIC"]["1"],1)
        self.assertEqual(s["reality_counts"]["UNKNOWN"],1)

class ArtifactTests(unittest.TestCase):
    def test_label_prefixes(self):
        for prefix in ("phishing:","spam:","legitimate:","[phishing]","ham:","phishing: spam:"):
            with self.subTest(prefix=prefix):
                self.assertEqual(feature_text({"subject":prefix+" Meeting","body":"Agenda"}),"meeting agenda")

    def test_injected_headers_and_folded_metadata(self):
        value={"body":"X-Dataset: phishing\n  injected corpus tag\nLabel=1\nGround-truth: phishing\nReview the report"}
        self.assertEqual(feature_text(value),"review the report")

    def test_folder_paths_removed(self):
        for path in ("train/phishing/message.txt",r"C:\dataset\spam\sample.eml","dataset/ham/"):
            with self.subTest(path=path):
                self.assertEqual(feature_text({"body":path+"\nReview report"}),"review report")

    def test_generation_markers(self):
        self.assertEqual(feature_text({"body":"Here is the generated phishing email:\nGenerated by Gemini 2.5 Flash\nPlease review"}),"please review")

    def test_external_metadata_never_becomes_features(self):
        a={"body":"Please review report"}
        b=dict(a,Label=1,source="smishx",reality="REAL",date="01/01/2025",authority=1,justif_authority="bad",filename="phishing.eml")
        self.assertEqual(feature_text(a),feature_text(b))

    def test_collector_markers(self):
        self.assertEqual(feature_text({"body":"SpaPhish SmishX phishing_pot Please review"}),"please review")

    def test_html_unicode_and_malformed(self):
        self.assertEqual(feature_text({"body":"<p>Ｃafé reunión</p><script>bad()</script>"}),"café reunión")
        for value in (None,[],{},{"body":[]},{"subject":None}):
            self.assertEqual(feature_text(value),"")

    def test_empty_after_scrubbing_dropped(self):
        self.assertIsNone(data.normalize_example({"body":"Phishing:","source":"a","label":1,"role":"train"}))

    def test_audit_contains_hashes_not_text(self):
        rows=batch(25)
        for r in rows:r["body"]="This is a repeated generation sentence for offline tests only."
        audit=data.artifact_audit(rows)
        self.assertEqual(len(audit["repeated_line_hashes"]),1)
        self.assertNotIn("generation sentence",json.dumps(audit))

class TemporalTests(unittest.TestCase):
    def test_day_first_date(self):
        self.assertEqual(data.parse_date("07/06/2024"),"2024-06-07")

    def test_bad_and_missing_dates_unknown(self):
        for value in ("31/02/2024","2024-01-01","2025",None,{}, ""):
            self.assertIsNone(data.parse_date(value))

    def test_temporal_boundaries(self):
        for day,expected in (("2022-12-31","train"),("2023-01-01","validation"),("2023-12-31","validation"),("2024-01-01","test"),("2025-12-31","test")):
            self.assertEqual(data.temporal_role(day,day),expected)

    def test_straddling_period_not_guessed(self):
        self.assertEqual(data.temporal_role("2022-01-01","2023-01-01"),"date_unknown")

    def test_reversed_interval_rejected(self):
        with self.assertRaises(ValueError):data.temporal_role("2024-01-01","2023-01-01")

    def test_future_outside_protocol_excluded(self):
        self.assertEqual(data.temporal_role("2026-01-01","2026-01-01"),"date_unknown")

    def test_future_training_rejected(self):
        with self.assertRaises(ValueError):
            data.assert_temporal_integrity([row(date_start="2024-01-01",date_end="2024-01-01")],[],[])

    def test_unknown_training_date_rejected(self):
        with self.assertRaises(ValueError):
            data.assert_temporal_integrity([row(date_quality="UNKNOWN")],[],[])

    def test_valid_old_bound_and_later_dates(self):
        train=[row(date_start="1995-01-01",date_end="2022-12-31",date_quality="DOCUMENTED_COLLECTION_BOUND")]
        val=[row(1,1,role="validation",date_start="2023-02-01",date_end="2023-02-01")]
        test=[row(2,1,role="test",date_start="2025-02-01",date_end="2025-02-01")]
        data.assert_temporal_integrity(train,val,test)

    def test_date_fields_not_features(self):
        self.assertEqual(row()["text"],row(date_start="2025-01-01")["text"])

class DeduplicationTests(unittest.TestCase):
    def test_exact_duplicate_and_provenance(self):
        a,b=row(),row(source="b")
        kept,stats,_=data.deduplicate([a,b])
        self.assertEqual(len(kept),1)
        self.assertEqual(stats["duplicates_removed"],1)
        self.assertEqual(kept[0]["sources"],["a","b"])

    def test_template_masks_identifiers(self):
        a=row(body="Please verify account 123456 now")
        b=row(1,source="b",body="Please verify account 654321 now")
        self.assertEqual(len(data.deduplicate([a,b])[0]),1)

    def test_conflicting_labels_quarantined(self):
        a,b=row(),row(source="b")
        b["label"]=1
        kept,stats,q=data.deduplicate([a,b])
        self.assertEqual(kept,[])
        self.assertEqual(stats["quarantine_rows"]["conflicting_labels"],2)

    def test_protected_prior_test_quarantined(self):
        a,b=row(),row(source="b",protected=True)
        self.assertFalse(data.deduplicate([a,b])[0])

    def test_cross_temporal_family_quarantined(self):
        a,b=row(),row(source="b",role="test")
        kept,stats,_=data.deduplicate([a,b])
        self.assertFalse(kept)
        self.assertEqual(stats["quarantine_rows"]["cross_partition_family"],2)

    def test_cross_external_family_quarantined(self):
        a,b=row(),row(source="smishx",role="external")
        self.assertFalse(data.deduplicate([a,b])[0])

    def test_mixed_reality_never_promoted_to_real(self):
        a,b=row(),row(source="b",reality="SYNTHETIC")
        self.assertEqual(data.deduplicate([a,b])[0][0]["reality"],"UNKNOWN")

    def test_date_range_conservatively_merged(self):
        a,b=row(),row(source="b",date_start="2021-03-01",date_end="2021-03-01")
        r=data.deduplicate([a,b])[0][0]
        self.assertEqual((r["date_start"],r["date_end"]),("2020-01-01","2021-03-01"))

    def test_missing_date_not_invented_from_other_copy(self):
        a,b=row(),row(source="b",date_start=None,date_end=None,date_quality="UNKNOWN")
        self.assertIsNone(data.deduplicate([a,b])[0][0]["date_start"])

    def test_reordering_reproducible(self):
        records=batch(10)
        self.assertEqual(data.deduplicate(records),data.deduplicate(list(reversed(records))))

    def test_near_duplicate_conflict_transitive(self):
        body=" ".join("word"+chr(97+i//26)+chr(97+i%26) for i in range(100))
        a=row(body=body)
        b=row(1,label=1,source="b",body=body)
        c=row(2,label=1,source="c",body=body.replace("wordba","differentword"))
        kept,stats,_=data.deduplicate([a,b,c])
        self.assertFalse(kept)
        self.assertEqual(stats["quarantine_rows"]["conflicting_labels"],3)

class IsolationAndGateTests(unittest.TestCase):
    def test_external_source_cannot_fit(self):
        with self.assertRaises(ValueError):data.assert_external_isolation([row(source="smishx")],[],[])

    def test_external_source_cannot_validate(self):
        with self.assertRaises(ValueError):data.assert_external_isolation([],[row(source="smishx")],[])

    def test_external_source_allowlist(self):
        with self.assertRaises(ValueError):data.assert_external_isolation([],[],[row(source="unknown")])

    def test_external_duplicate_rejected(self):
        a=row()
        b=dict(a,source="smishx",sources=["smishx"])
        with self.assertRaises(ValueError):data.assert_external_isolation([a],[],[b])

    def test_real_and_synthetic_metrics_separate(self):
        rows=[row(),row(1,1),row(2,reality="SYNTHETIC"),row(3,1,reality="SYNTHETIC")]
        result=evaluate.cohorts(rows,[.1,.9,.9,.1],.5)
        self.assertEqual(result["by_reality"]["REAL"]["pooled"]["accuracy"],1.)
        self.assertEqual(result["by_reality"]["SYNTHETIC"]["pooled"]["accuracy"],0.)
        self.assertIsNone(result["by_reality"]["UNKNOWN"])
        self.assertIsNone(result["by_reality_class"]["REAL_malicious"]["false_positive_rate"])

    def test_year_cohorts(self):
        result=evaluate.cohorts([row(date_start="2024-03-01",date_end="2024-03-01")],[.1],.5)
        self.assertEqual(result["by_year"]["2024"]["count"],1)

    def test_empty_evaluation_not_success(self):
        self.assertIsNone(evaluate.cohorts([],[],.5)["overall"])

    def test_all_extra_gates_can_pass_with_sufficient_evidence(self):
        m=perfect_evaluation()
        self.assertTrue(evaluate.extra_gates(m,m,perfect_evidence(),{"0":20,"1":20})["passed_all"])

    def test_predominantly_synthetic_rejected(self):
        m=perfect_evaluation();e=perfect_evidence();e["synthetic_malicious_fraction"]=.5001
        self.assertIn("synthetic_dominance",evaluate.extra_gates(m,m,e,{"0":20,"1":20})["failed"])

    def test_unknown_dominance_rejected(self):
        m=perfect_evaluation();e=perfect_evidence();e["unknown_malicious_fraction"]=.11
        self.assertIn("unknown_malicious_provenance",evaluate.extra_gates(m,m,e,{"0":20,"1":20})["failed"])

    def test_sms_does_not_count_as_modern_email(self):
        r=row(label=1,channel="sms",date_start="2025-01-01",date_end="2025-01-01")
        e=evaluate.evidence_counts([r],[r])
        self.assertEqual(e["modern_real_email_phishing"],0)
        self.assertEqual(e["external_real_email_counts"]["1"],0)

    def test_real_modern_support_requires_documented_dates(self):
        e=evaluate.evidence_counts([row(label=1,date_start="2025-01-01",date_end="2025-01-01",date_quality="UNKNOWN")],[])
        self.assertEqual(e["modern_real_email_phishing"],0)

    def test_missing_evidence_fails_closed(self):
        self.assertFalse(evaluate.extra_gates(None,None,{}, {})["passed_all"])

    def test_each_numeric_performance_gate_enforced(self):
        m=perfect_evaluation()
        for phase in ("temporal","external"):
            for key,bad in (("precision",.89),("recall",.94),("false_positive_rate",.06),("f1",.89),("brier_score",.11),("ece_10_equal_width",.06)):
                a,b=copy.deepcopy(m),copy.deepcopy(m)
                (a if phase=="temporal" else b)["pooled"][key]=bad
                with self.subTest(phase=phase,key=key):
                    self.assertIn(phase+"_"+key,evaluate.extra_gates(a,b,perfect_evidence(),{"0":20,"1":20})["failed"])

    def test_worst_source_cannot_hide_in_pooled_score(self):
        a=perfect_evaluation();a["source_summary"]["worst_source_error"]=.11
        self.assertIn("external_worst_source_error",evaluate.extra_gates(perfect_evaluation(),a,perfect_evidence(),{"0":20,"1":20})["failed"])

    def test_inherited_policy_unchanged(self):
        frozen=json.loads((ROOT/"reports/candidate_v2_selection.json").read_text())["policy"]
        self.assertEqual(evaluate.V2_POLICY,frozen)

    def test_failed_inherited_gate_blocks_validation(self):
        self.assertFalse(evaluate.candidate_status(True,{"passed_all":False},{"passed_all":True})["validated"])

    def test_pass_never_auto_activates(self):
        s=evaluate.candidate_status(True,{"passed_all":True},{"passed_all":True})
        self.assertEqual(s["status"],"VALIDATED")
        self.assertFalse(s["active"])
        self.assertFalse(s["activation_recommended"])

    def test_final_test_cannot_promote_nonselected_model(self):
        s=evaluate.candidate_status(False,{"passed_all":True},{"passed_all":True})
        self.assertEqual(s["status"],"UNVALIDATED")

    def test_source_identity_diagnostic_is_separate(self):
        train=[];val=[]
        for source,phrase,offset in (("a","orchard harvest apple pear fruit",0),("b","ocean vessel nautical harbor sailor",100)):
            train+=batch(40,offset=offset,source=source,body=phrase)
            val+=batch(10,offset=offset+50,source=source,body=phrase)
        result=evaluate.source_predictability(train,val)
        self.assertEqual(result["validation_accuracy"],1.)
        self.assertEqual(result["majority_source_baseline"],.5)

    def test_original_model_hashes(self):
        self.assertEqual(evaluate.verify_legacy(),evaluate.LEGACY_HASHES)

    def test_original_loader_does_not_reference_research_namespace(self):
        runtime=(ROOT.parent/"backend/analyzers/nlp_detector.py").read_text()
        self.assertNotIn("validation_corpus",runtime)
        self.assertNotIn("candidate_real_world",runtime)

class LockedExperimentTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.temp=TemporaryDirectory()
        cls.base=Path(cls.temp.name);cls.dataset=cls.base/"data";cls.dataset.mkdir()
        parts={"train":batch(80), "validation":batch(60,offset=100,role="validation",date_start="2023-04-01",date_end="2023-04-01"),
               "validation_historical":batch(20,offset=200,role="validation_historical"),
               "test":batch(40,offset=300,role="test",date_start="2024-06-01",date_end="2024-06-01"),
               "external":batch(40,offset=400,source="smishx",role="external",channel="sms"),
               "date_unknown":[],"synthetic_stress":[]}
        cls.manifest={"splits":{},"recipe":{"transfer_pairs":[],
            "evidence":{"independent_real_both_class_sources":0,"representative_external_holdout":False}}}
        for name,rows in parts.items():
            p=cls.dataset/(name+".jsonl")
            p.write_text("".join(json.dumps(r)+"\n" for r in rows))
            cls.manifest["splits"][name]={"sha256":digest(p.read_bytes())}
        write_json(cls.dataset/"manifest.json",cls.manifest)
        cls.run_dir=cls.base/"run";cls.lock=cls.base/"selection.json"
        m=perfect_evaluation()
        source_tests={"summary":m["source_summary"],"all_folds_evaluated":True,
                      "paired_source_transfer":[{"status":"EVALUATED","evaluation":m}]}
        reads=[]
        real_reader=evaluate.checked_rows
        def reader(dataset,part,manifest):
            reads.append(part)
            if part in {"test","external","date_unknown","synthetic_stress"}:
                raise AssertionError("Selection opened held-out corpus")
            return real_reader(dataset,part,manifest)
        with patch.object(evaluate,"checked_rows",side_effect=reader),patch.object(evaluate,"source_evaluation",return_value=source_tests),patch.object(evaluate,"source_predictability",return_value={"scope":"fixture"}),redirect_stdout(io.StringIO()):
            cls.selection=evaluate.select(cls.dataset,cls.run_dir,cls.lock)
        cls.reads=reads

    @classmethod
    def tearDownClass(cls):
        cls.temp.cleanup()

    def test_selection_never_reads_holdouts(self):
        self.assertEqual(set(self.reads),{"train","validation","validation_historical"})

    def test_all_four_lightweight_candidates(self):
        self.assertEqual(set(self.selection["candidates"]),set(CANDIDATES))

    def test_thresholds_use_later_validation_only(self):
        for c in self.selection["candidates"].values():
            self.assertEqual(c["threshold_origin"],"SpaPhish 2023 only")

    def test_selection_starts_inactive_research(self):
        for c in self.selection["candidates"].values():
            self.assertFalse(c["active"]);self.assertEqual(c["status"],"RESEARCH")

    def test_lock_verifies(self):
        evaluate.verify_lock(self.dataset,self.run_dir,self.lock)

    def test_changed_gate_rejected(self):
        with patch.dict(evaluate.EXTRA_POLICY,{"external_min_recall":.5}),self.assertRaises(ValueError):
            evaluate.verify_lock(self.dataset,self.run_dir,self.lock)

    def test_changed_code_rejected(self):
        with patch.object(evaluate,"code_hashes",return_value={}),self.assertRaises(ValueError):
            evaluate.verify_lock(self.dataset,self.run_dir,self.lock)

    def test_lock_tampering_rejected(self):
        p=self.base/"tampered.json";p.write_bytes(self.lock.read_bytes()+b" ")
        with self.assertRaises(ValueError):evaluate.verify_lock(self.dataset,self.run_dir,p)

    def test_selection_cannot_overwrite(self):
        with self.assertRaises(FileExistsError):evaluate.select(self.dataset,self.run_dir,self.lock)

    def test_model_binary_tampering_rejected(self):
        name=CANDIDATES[0];p=self.run_dir/(name+".joblib");original=p.read_bytes()
        try:
            p.write_bytes(original+b"corruption")
            with self.assertRaises(ValueError):evaluate.verify_lock(self.dataset,self.run_dir,self.lock)
        finally:p.write_bytes(original)

    def test_single_use_marker_prevents_reopening(self):
        marker=Path(str(self.lock)+".test-opened");marker.write_text("previously opened")
        try:
            with self.assertRaises(FileExistsError):
                evaluate.finalize(self.dataset,self.run_dir,self.lock,self.base/"models",self.base/"final.json")
        finally:marker.unlink()

    def test_complete_finalize_writes_inactive_metadata_without_switching_choice(self):
        import shutil
        with TemporaryDirectory() as directory:
            base=Path(directory)
            dataset=base/"data";run=base/"run";lock=base/"selection.json"
            shutil.copytree(self.dataset,dataset);shutil.copytree(self.run_dir,run);shutil.copyfile(self.lock,lock)
            with redirect_stdout(io.StringIO()):
                result=evaluate.finalize(dataset,run,lock,base/"models",base/"final.json")
            self.assertEqual(result["selected_model"],self.selection["selected_model"])
            for name in CANDIDATES:
                meta=json.loads((base/"models"/name/"metadata.json").read_text())
                self.assertFalse(meta["active"])
                self.assertEqual(meta["status"],"UNVALIDATED")
            self.assertTrue(Path(str(lock)+".test-opened").exists())
            with self.assertRaises(FileExistsError):
                evaluate.finalize(dataset,run,lock,base/"another-model",base/"another-final.json")

    def test_loader_resolves_from_different_working_directory(self):
        import os
        before=Path.cwd()
        try:
            os.chdir(self.base)
            self.assertEqual(evaluate.verify_legacy(),evaluate.LEGACY_HASHES)
        finally:os.chdir(before)

class FetchSafetyTests(unittest.TestCase):
    def test_unreviewed_asset_refused_before_network(self):
        with TemporaryDirectory() as d:
            p=Path(d)/"recipe.json";write_json(p,{"assets":[{"filename":"payload.zip"}]})
            with patch.object(fetch,"RECIPE",p),patch.object(fetch.requests,"get") as get,self.assertRaises(ValueError):
                fetch.fetch(Path(d)/"raw")
            get.assert_not_called()

    def test_wrong_existing_checksum_rejected(self):
        with TemporaryDirectory() as d:
            p=Path(d)/"recipe.json";raw=Path(d)/"raw";raw.mkdir();(raw/"smishx.csv").write_text("bad")
            write_json(p,{"assets":[{"filename":"smishx.csv","url":"https://raw.githubusercontent.com/example/data.csv","bytes":3,"sha256":"0"*64}]})
            with patch.object(fetch,"RECIPE",p),self.assertRaises(ValueError):fetch.fetch(raw)
